import type { ExperienceItem } from "./types";

export const experience: readonly ExperienceItem[] = [
    {
        id: "hello-world",
        company: "Hello World",
        title: "Organizer & Board Member",
        startDate: "2026-01",
        endDate: null,
        location: "West Lafayette, IN",
        highlights: [
            "Working towards securing $50,000+ from corporate sponsors, up from $40,000 last year.",
            "Inviting companies and their recruiters to interact with the competing students and share their own company's initiatives.",
        ],
    },
    {
        id: "purdue-electric-racing",
        company: "Purdue Electric Racing",
        title: "Electronics Team Member",
        startDate: "2025-09",
        endDate: null,
        location: "West Lafayette, IN",
        highlights: [
            "Developed embedded firmware for the team’s Formula-style electric vehicle using an STM32F4 Discovery board.",
            "Implemented low-level control of dashboard LEDs and driver inputs using GPIO configuration and interrupt-driven routines.",
            "Designed and tested safety-critical firmware to process pedal torque requests using ADC sampling and signal filtering.",
        ],
    },
    {
        id: "embedded-systems-purdue",
        company: "Embedded Systems @ Purdue",
        title: "Embedded Software Developer | Harmonicore Project",
        startDate: "2025-08",
        endDate: "2025-12",
        location: "West Lafayette, IN",
        highlights: [
            "Implemented Fast Fourier Transform IP blocks in SystemVerilog for real-time, low latency Digital Signal Processing workloads.",
            "Designed Register-Transfer Level designs for algorithmic logic flow and integrated modules with FPGA-based hardware systems.",
            "Optimized HDL modules for resource-constrained environments, increasing processing efficiency under limited multipliers.",
        ],
    },
    {
        id: "data-mine-purdue",
        company: "The Data Mine-Purdue University",
        title: "Developer",
        startDate: "2025-08",
        endDate: "2025-12",
        location: "West Lafayette, IN",
        highlights: [
            "Processed and analyzed large datasets using Python (Pandas, NumPy) and R, extracting insights to guide decisions.",
            "Implemented high-performance computing (HPC) optimizations and containerized workflows for efficiency.",
            "Built structured datasets via web scraping and cleaning pipelines, enabling downstream analytics.",
        ],
    },
    {
        id: "purdue-lunabotics",
        company: "Purdue Lunabotics",
        title: "Software Developer",
        startDate: "2025-08",
        endDate: "2025-11",
        location: "West Lafayette, IN",
        highlights: [
            "Implemented autonomous navigation algorithms inspired by A* search to traverse simulated lunar terrain quickly and efficiently.",
            "Converted legacy competition codebase from ROS1 to ROS2, reducing latency by 20% and improving system responsiveness.",
        ],
    },
    {
        id: "brookhaven-national-lab",
        company: "Brookhaven National Laboratory",
        title: "Research Intern",
        startDate: "2024-07",
        endDate: "2024-08",
        location: "New York, NY",
        highlights: [
            "Built an automated defect detection system for silicon wafers using Python, OpenCV, and a 3D printer-mounted camera.",
            "Optimized the image processing pipeline to improve defect detection accuracy and throughput across multiple wafer types.",
            "Collaborated with research mentors to enhance the project’s sustainability for ongoing semiconductor studies.",
        ],
    },
    {
        id: "statice-health-international",
        company: "Statice Health International",
        title: "Founder, Blogging Department",
        startDate: "2023-01",
        endDate: "2025-05",
        location: "Syosset, NY",
        highlights: [
            "Created and managed a public health blog raising awareness on conditions such as PTSD, epilepsy, and cancer.",
            "Trained and mentored dozens of volunteer writers; edited over 20 articles for clarity, accuracy, and accessibility.",
            "Blogs reached 150M+ total readers.",
        ],
    },
    {
        id: "k12-stem-camp",
        company: "K12 STEM Camp",
        title: "Assistant Teacher",
        startDate: "2023-05",
        endDate: "2023-08",
        location: "Melville, NY",
        highlights: [
            "Taught elementary school (K-5) children the basics of robotics in an interactive and fun environment.",
            "Focused on making STEM concepts—programming, engineering, and mechanics—fun and easy to understand through hands-on activities like building simple robots and programming them to complete tasks.",
        ],
    },
    {
        id: "first-robotics",
        company: "FIRST",
        title: "Alumnus, Mentor (FRC 9016)",
        startDate: "2022-09",
        endDate: null,
        location: "Syosset, NY",
        highlights: [
            "Mentored 10 teammates in debugging, quality assurance, and system integration, contributing towards the team’s continued success.",
            "Developed finite state machine automation in Java, leading to the #1 ranked autonomous routine in regional play.",
            "Integrated computer vision for localization using SolvePnP, leading to the team’s first Regional Championship [NYLI2, 2024].",
            "Led team of 40+ members across 6 competitions, qualifying for the World Championships three years consecutively.",
        ],
    },
];
