import type { ExperienceItem } from "./types";

export const experience: readonly ExperienceItem[] = [
    {
        id: "hello-world",
        company: "Hello World",
        title: "Organizer & Board Member",
        startDate: "2026-01",
        endDate: null,
        location: "West Lafayette, IN",
        highlights: [
            "Working towards securing $50,000+ from corporate sponsors, up from $40,000 last year.",
            "Inviting companies and their recruiters to interact with the competing students and share their own company's initiatives.",
        ],
    },
    {
        id: "purdue-electric-racing",
        company: "Purdue Electric Racing",
        title: "Electronics Team Member",
        startDate: "2025-09",
        endDate: null,
        location: "West Lafayette, IN",
        highlights: [
            "Developed embedded firmware for the team’s Formula-style electric vehicle using an STM32F4 Discovery board.",
            "Implemented low-level control of dashboard LEDs and driver inputs using GPIO configuration and interrupt-driven routines.",
            "Designed and tested safety-critical firmware to process pedal torque requests using ADC sampling and signal filtering.",
        ],
    },
    {
        id: "embedded-systems-purdue",
        company: "Embedded Systems @ Purdue",
        title: "Embedded Software Developer | Harmonicore Project",
        startDate: "2025-08",
        endDate: "2025-12",
        location: "West Lafayette, IN",
        highlights: [
            "Designed and implemented FPGA-based digital signal processing (DSP) modules for real-time autotuning.",
            "Programmed FPGA logic using SystemVerilog to realize low-latency, efficient signal transformations.",
            "Optimized HDL modules for timing and resource efficiency, enhancing the core’s responsiveness during live signal processing.",
        ],
    },
    {
        id: "data-mine-purdue",
        company: "The Data Mine-Purdue University",
        title: "Developer",
        startDate: "2025-08",
        endDate: "2025-12",
        location: "West Lafayette, IN",
        highlights: [
            "Processed and analyzed large datasets using Python (Pandas, NumPy) and R, extracting insights to guide decisions.",
            "Implemented high-performance computing (HPC) optimizations and containerized workflows for efficiency.",
            "Built structured datasets via web scraping and cleaning pipelines, enabling downstream analytics.",
        ],
    },
    {
        id: "purdue-lunabotics",
        company: "Purdue Lunabotics",
        title: "Software Developer",
        startDate: "2025-08",
        endDate: "2025-11",
        location: "West Lafayette, IN",
        highlights: [
            "Implemented autonomous navigation algorithms stemming from A* to reliably traverse in simulated lunar environments.",
            "Integrated LiDAR sensors with control systems to improve excavation accuracy and obstacle detection.",
            "Optimized communication between software modules with ROS to ensure realtime decision making during missions.",
        ],
    },
    {
        id: "brookhaven-national-lab",
        company: "Brookhaven National Laboratory",
        title: "Research Intern",
        startDate: "2024-07",
        endDate: "2024-08",
        location: "New York, NY",
        highlights: [
            "Designed and implemented an automated defect detection system using a camera mounted to a 3D printer platform.",
            "Wrote Python scripts integrating OpenCV to identify silicon wafer defects critical for photolithography.",
            "Contributed to semiconductor analysis for high-precision chip manufacturing under professional mentorship.",
        ],
    },
    {
        id: "statice-health-international",
        company: "Statice Health International",
        title: "Founder, Blogging Department",
        startDate: "2023-01",
        endDate: "2025-05",
        location: "Syosset, NY",
        highlights: [
            "Created and managed a public health blog raising awareness on conditions such as PTSD, epilepsy, and cancer.",
            "Trained and mentored dozens of volunteer writers; edited over 20 articles for clarity, accuracy, and accessibility.",
            "Blogs reached 150M+ total readers.",
        ],
    },
    {
        id: "k12-stem-camp",
        company: "K12 STEM Camp",
        title: "Assistant Teacher",
        startDate: "2023-05",
        endDate: "2023-08",
        location: "Melville, NY",
        highlights: [
            "Taught elementary school (K-5) children the basics of robotics in an interactive and fun environment.",
            "Focused on making STEM concepts—programming, engineering, and mechanics—fun and easy to understand through hands-on activities like building simple robots and programming them to complete tasks.",
        ],
    },
    {
        id: "first-robotics",
        company: "FIRST",
        title: "Alumnus, Mentor (FRC 9016)",
        startDate: "2022-09",
        endDate: null,
        location: "Syosset, NY",
        highlights: [
            "Mentored 10 teammates in debugging, quality assurance, and system integration, contributing towards the team’s continued success.",
            "Developed finite state machine automation in Java, leading to the #1 ranked autonomous routine in regional play.",
            "Integrated computer vision for localization using SolvePnP, leading to the team’s first Regional Championship [NYLI2, 2024].",
            "Led team of 40+ members across 6 competitions, qualifying for the World Championships three years consecutively.",
        ],
    },
];
